import type { Metadata } from "next";
// import { Roboto, Mulish } from "next/font/google";
import Headr from "@/src/app/_Components/Header/Headr";
import "./globals.css";

// const Robotofont = Roboto({
//   variable: "--font-roboto",
//   subsets: ["greek"],
//   fallback: ["Arial"]
// });
// const Mulishfont = Mulish({
//   variable: "--font-Mulishfont",
//   subsets: ["latin"],
//   fallback: ["Arial"],
//   display: "swap"
// });

export const metadata: Metadata = {
  title: {
    template: "%s | News App",
    default: ''
  },
  description: "Generated by create next app",
};
interface Iprops {
  children: React.ReactNode;
  // usNews: React.ReactNode;
  // ukNews: React.ReactNode;
}
export default function RootLayout({ children  }: Iprops) {

  return (
    <html lang="en" >
      <body>
        <Headr />
        {children}
        {false && (
          <>
            {/* <section> {usNews}</section>
            <section> {ukNews}</section> */}
          </>
        )}
      </body>
    </html>
  );
}
