import type { Metadata } from "next";
import { Roboto, Mulish } from "next/font/google";
import Headr from "@/src/app/_Components/Header/Headr";
import "./globals.css";
import { Providers } from "../providers/provider";
import Footer from "../_Components/footer/Footer";

const Robotofont = Roboto({
  variable: "--font-roboto",
  subsets: ["greek"],
  fallback: ["Arial"]
});
const Mulishfont = Mulish({
  variable: "--font-Mulishfont",
  subsets: ["latin"],
  fallback: ["Arial"],
  display: "swap"
});

export const metadata: Metadata = {
  title: {
    template: "%s | News App",
    default: ''
  },
  description: "Generated by create next app",
};
interface Iprops {
  children: React.ReactNode;

}
export default function RootLayout({ children }: Iprops) {

  return (
    <html lang="en" className={`${Robotofont.variable} ${Mulishfont.variable}`}>
      <body>
        <Providers>
          <Headr />
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
