// app/(second)/layout.tsx
import type { Metadata } from "next";
import { Roboto, Mulish } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import { Providers } from "../providers/provider";
import Headr from "../_Components/Header/Headr";

const Robotofont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  fallback: ["Arial"]
});
const Mulishfont = Mulish({
  variable: "--font-Mulishfont",
  subsets: ["latin"],
  fallback: ["Arial"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${Robotofont.variable} ${Mulishfont.variable}`}>
        <Providers>
          <Headr />
          {children}
        </Providers>
      </body>
    </html>
  );
}
