import type { Metadata } from "next";
import { Roboto, Mulish } from "next/font/google";
import Headr from "@/_Components/Header/Headr";

import "./globals.css";

const Robotofont = Roboto({
  variable: "--font-roboto",
  subsets: ["greek"],
  fallback: ["Arial"]
});
const Mulishfont = Mulish({
  variable: "--font-Mulishfont",
  subsets: ["latin"],
  fallback: ["Arial"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "News App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className={`${Mulishfont.className} ${Robotofont.className} `}>
      <body>
        <Headr/>
        {children}
      </body>
    </html>
  );
}
